// src/components/asyncapi/asyncapi-viewer.tsx
// AsyncAPI Viewer — 3 modes: Documentation (CDN), Edit (form), JSON (raw editable)
// v3: Added inline editing of business fields + raw JSON save
//
// Placement: frontend/src/components/asyncapi/asyncapi-viewer.tsx

"use client";

import React, { useRef, useEffect, useState, useCallback } from "react";
import {
  Eye, Code, Copy, Check, Download, Sparkles, Pencil,
  AlertCircle, Loader2, Save, X, Plus, Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface AsyncApiViewerProps {
  schema: any;
  isAutoGenerated?: boolean;
  onExportYaml?: () => void;
  onSave?: (updatedSpec: Record<string, unknown>) => Promise<void>;
}

export function AsyncApiViewer({
  schema,
  isAutoGenerated = true,
  onExportYaml,
  onSave,
}: AsyncApiViewerProps) {
  const [activeTab, setActiveTab] = useState<"docs" | "edit" | "raw">("docs");
  const [copied, setCopied] = useState(false);
  const [renderState, setRenderState] = useState<"loading" | "ok" | "error">("loading");
  const containerRef = useRef<HTMLDivElement>(null);

  // ── Edit form state ──
  const [editTitle, setEditTitle] = useState("");
  const [editDescription, setEditDescription] = useState("");
  const [editOwner, setEditOwner] = useState("");
  const [editServerHost, setEditServerHost] = useState("");
  const [editTags, setEditTags] = useState<string[]>([]);
  const [newTag, setNewTag] = useState("");
  const [editSaving, setEditSaving] = useState(false);
  const [editError, setEditError] = useState<string | null>(null);
  const [editSuccess, setEditSuccess] = useState(false);

  // ── Raw JSON state ──
  const [rawJson, setRawJson] = useState("");
  const [rawSaving, setRawSaving] = useState(false);
  const [rawError, setRawError] = useState<string | null>(null);
  const [rawSuccess, setRawSuccess] = useState(false);
  const [rawJsonValid, setRawJsonValid] = useState(true);

  const rawSpec = JSON.stringify(schema, null, 2);

  // ── Init edit form from schema ──
  useEffect(() => {
    if (!schema || typeof schema !== "object") return;
    const info = schema.info || {};
    setEditTitle(info.title || "");
    setEditDescription(info.description || "");
    setEditOwner(info.contact?.name || "");
    setEditTags((info.tags || []).map((t: any) => t.name || t));

    const servers = schema.servers || {};
    const firstServer = Object.values(servers)[0] as any;
    setEditServerHost(firstServer?.host || "");
  }, [schema]);

  // ── Init raw JSON ──
  useEffect(() => {
    setRawJson(JSON.stringify(schema, null, 2));
    setRawJsonValid(true);
  }, [schema]);

  // ── CDN Render ──
  useEffect(() => {
    if (activeTab !== "docs" || !containerRef.current) return;
    setRenderState("loading");

    let cancelled = false;
    let retryTimer: NodeJS.Timeout;

    function tryRender() {
      if (cancelled) return;
      const standalone =
        (window as any).AsyncApiStandalone ||
        (window as any).AsyncApiComponent ||
        (window as any).asyncApiReactComponent;

      if (!standalone) {
        retryTimer = setTimeout(tryRender, 300);
        return;
      }

      try {
        if (standalone.render) {
          standalone.render(
            { schema: typeof schema === "string" ? schema : JSON.stringify(schema) },
            containerRef.current
          );
        } else if (standalone.default?.render) {
          standalone.default.render(
            { schema: typeof schema === "string" ? schema : JSON.stringify(schema) },
            containerRef.current
          );
        }
        if (!cancelled) setRenderState("ok");
      } catch (err) {
        console.error("AsyncAPI render error:", err);
        if (!cancelled) setRenderState("error");
      }
    }

    retryTimer = setTimeout(tryRender, 100);

    return () => {
      cancelled = true;
      clearTimeout(retryTimer);
      if (containerRef.current) containerRef.current.innerHTML = "";
    };
  }, [schema, activeTab]);

  // ── Copy ──
  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(rawSpec);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [rawSpec]);

  // ── Save Edit Form ──
  const handleSaveEdit = useCallback(async () => {
    if (!onSave || !schema) return;
    setEditSaving(true);
    setEditError(null);
    setEditSuccess(false);

    try {
      const updated = JSON.parse(JSON.stringify(schema));

      // Apply form fields
      if (!updated.info) updated.info = {};
      updated.info.title = editTitle;
      updated.info.description = editDescription;

      if (editOwner) {
        if (!updated.info.contact) updated.info.contact = {};
        updated.info.contact.name = editOwner;
      }

      updated.info.tags = editTags.map((t) => ({ name: t }));

      // Update server host
      if (editServerHost && updated.servers) {
        const serverKeys = Object.keys(updated.servers);
        if (serverKeys.length > 0) {
          updated.servers[serverKeys[0]].host = editServerHost;
        }
      }

      await onSave(updated);
      setEditSuccess(true);
      setTimeout(() => setEditSuccess(false), 3000);
    } catch (err: any) {
      setEditError(err?.detail || err?.message || "Failed to save");
    } finally {
      setEditSaving(false);
    }
  }, [onSave, schema, editTitle, editDescription, editOwner, editServerHost, editTags]);

  // ── Save Raw JSON ──
  const handleSaveRaw = useCallback(async () => {
    if (!onSave) return;
    setRawSaving(true);
    setRawError(null);
    setRawSuccess(false);

    try {
      const parsed = JSON.parse(rawJson);
      await onSave(parsed);
      setRawSuccess(true);
      setTimeout(() => setRawSuccess(false), 3000);
    } catch (err: any) {
      if (err instanceof SyntaxError) {
        setRawError("Invalid JSON syntax");
      } else {
        setRawError(err?.detail || err?.message || "Failed to save");
      }
    } finally {
      setRawSaving(false);
    }
  }, [onSave, rawJson]);

  // ── Validate raw JSON on change ──
  const handleRawChange = useCallback((value: string) => {
    setRawJson(value);
    try {
      JSON.parse(value);
      setRawJsonValid(true);
    } catch {
      setRawJsonValid(false);
    }
  }, []);

  // ── Tag management ──
  const addTag = useCallback(() => {
    const tag = newTag.trim();
    if (tag && !editTags.includes(tag)) {
      setEditTags((prev) => [...prev, tag]);
      setNewTag("");
    }
  }, [newTag, editTags]);

  const removeTag = useCallback((tag: string) => {
    setEditTags((prev) => prev.filter((t) => t !== tag));
  }, []);

  return (
    <div className="flex flex-col h-[850px] border rounded-xl overflow-hidden bg-card shadow-sm">
      {/* Header bar */}
      <div className="flex items-center justify-between px-4 py-3 bg-muted/50 border-b">
        <div className="flex gap-1 p-1 bg-muted rounded-lg">
          <button
            onClick={() => setActiveTab("docs")}
            className={cn(
              "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
              activeTab === "docs"
                ? "bg-background shadow-sm text-primary"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            <Eye size={14} /> Docs
          </button>
          {onSave && (
            <button
              onClick={() => setActiveTab("edit")}
              className={cn(
                "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
                activeTab === "edit"
                  ? "bg-background shadow-sm text-primary"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              <Pencil size={14} /> Edit
            </button>
          )}
          <button
            onClick={() => setActiveTab("raw")}
            className={cn(
              "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
              activeTab === "raw"
                ? "bg-background shadow-sm text-primary"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            <Code size={14} /> JSON
          </button>
        </div>

        <div className="flex items-center gap-2">
          <Badge variant={isAutoGenerated ? "secondary" : "outline"}>
            {isAutoGenerated ? (
              <><Sparkles size={12} className="mr-1" /> Auto-generated</>
            ) : (
              <><Pencil size={12} className="mr-1" /> Edited</>
            )}
          </Badge>
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? <><Check size={14} className="mr-1" /> Copied</> : <><Copy size={14} className="mr-1" /> Copy</>}
          </Button>
          {onExportYaml && (
            <Button variant="default" size="sm" onClick={onExportYaml}>
              <Download size={14} className="mr-1" /> YAML
            </Button>
          )}
        </div>
      </div>

      {/* Content area */}
      <div className="flex-1 overflow-auto">

        {/* ── Tab: Documentation (CDN render) ── */}
        {activeTab === "docs" && (
          <div className="relative">
            {renderState === "loading" && (
              <div className="flex items-center justify-center h-64">
                <Loader2 size={24} className="animate-spin text-muted-foreground" />
              </div>
            )}
            {renderState === "error" && (
              <div className="flex items-center justify-center h-64 text-destructive">
                <AlertCircle size={20} className="mr-2" />
                Failed to render — try the JSON tab.
              </div>
            )}
            <div
              ref={containerRef}
              className="asyncapi-custom-container p-4 bg-white"
              style={{ color: "#1a1a1a", display: renderState === "loading" ? "none" : "block" }}
            />
          </div>
        )}

        {/* ── Tab: Edit (business fields form) ── */}
        {activeTab === "edit" && (
          <div className="p-6 space-y-6 max-w-2xl">
            <div>
              <p className="text-sm text-muted-foreground mb-4">
                Edit business metadata. Changes will be saved to the spec and marked as manually edited.
              </p>
            </div>

            {/* Title */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Title
              </label>
              <Input
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
                placeholder="e.g. Order Events"
                className="h-9"
              />
            </div>

            {/* Description */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Description
              </label>
              <textarea
                value={editDescription}
                onChange={(e) => setEditDescription(e.target.value)}
                placeholder="Describe what this event represents..."
                rows={3}
                className="w-full rounded-md border border-border bg-background px-3 py-2 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-cyan-400/30"
              />
            </div>

            {/* Owner / Contact */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Owner / Contact
              </label>
              <Input
                value={editOwner}
                onChange={(e) => setEditOwner(e.target.value)}
                placeholder="e.g. orders-team"
                className="h-9"
              />
            </div>

            {/* Server host */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Server host
              </label>
              <Input
                value={editServerHost}
                onChange={(e) => setEditServerHost(e.target.value)}
                placeholder="e.g. kafka:9092"
                className="h-9"
              />
            </div>

            {/* Tags */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Tags
              </label>
              <div className="flex flex-wrap gap-1.5 mb-2">
                {editTags.map((tag) => (
                  <span
                    key={tag}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs bg-cyan-500/10 text-cyan-400 border border-cyan-500/20"
                  >
                    {tag}
                    <button onClick={() => removeTag(tag)} className="hover:text-destructive">
                      <X size={10} />
                    </button>
                  </span>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  value={newTag}
                  onChange={(e) => setNewTag(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addTag())}
                  placeholder="Add a tag..."
                  className="h-8 text-sm flex-1"
                />
                <Button variant="outline" size="sm" className="h-8" onClick={addTag} disabled={!newTag.trim()}>
                  <Plus size={12} />
                </Button>
              </div>
            </div>

            {/* Save / Error / Success */}
            <div className="flex items-center gap-3 pt-2">
              <Button
                onClick={handleSaveEdit}
                disabled={editSaving}
                size="sm"
                className="gap-1.5"
              >
                {editSaving ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} />}
                {editSaving ? "Saving..." : "Save changes"}
              </Button>

              {editSuccess && (
                <span className="flex items-center gap-1 text-xs text-emerald-400">
                  <Check size={14} /> Saved
                </span>
              )}

              {editError && (
                <span className="flex items-center gap-1 text-xs text-destructive">
                  <AlertCircle size={14} /> {editError}
                </span>
              )}
            </div>
          </div>
        )}

        {/* ── Tab: JSON (editable raw) ── */}
        {activeTab === "raw" && (
          <div className="relative h-full flex flex-col">
            {/* Toolbar */}
            {onSave && (
              <div className="flex items-center justify-between px-4 py-2 border-b border-zinc-800 bg-zinc-950">
                <div className="flex items-center gap-2">
                  {!rawJsonValid && (
                    <span className="flex items-center gap-1 text-xs text-destructive">
                      <AlertCircle size={12} /> Invalid JSON
                    </span>
                  )}
                  {rawSuccess && (
                    <span className="flex items-center gap-1 text-xs text-emerald-400">
                      <Check size={12} /> Saved
                    </span>
                  )}
                  {rawError && (
                    <span className="flex items-center gap-1 text-xs text-destructive">
                      <AlertCircle size={12} /> {rawError}
                    </span>
                  )}
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-7 text-xs gap-1"
                  onClick={handleSaveRaw}
                  disabled={rawSaving || !rawJsonValid}
                >
                  {rawSaving ? <Loader2 size={12} className="animate-spin" /> : <Save size={12} />}
                  {rawSaving ? "Saving..." : "Save JSON"}
                </Button>
              </div>
            )}
            {/* Editor */}
            <textarea
              value={rawJson}
              onChange={(e) => handleRawChange(e.target.value)}
              readOnly={!onSave}
              spellCheck={false}
              className={cn(
                "flex-1 w-full bg-zinc-950 p-6 font-mono text-sm text-emerald-400 resize-none focus:outline-none",
                !rawJsonValid && "text-red-400",
                !onSave && "cursor-default"
              )}
            />
          </div>
        )}
      </div>
    </div>
  );
}