"use client";

import React, { useRef, useEffect, useState, useCallback } from "react";
import { Eye, Code, Copy, Check, Download, Sparkles, Pencil, AlertCircle, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

interface AsyncApiViewerProps {
  schema: any;
  isAutoGenerated?: boolean;
  onExportYaml?: () => void;
}

export function AsyncApiViewer({
  schema,
  isAutoGenerated = true,
  onExportYaml,
}: AsyncApiViewerProps) {
  const [activeTab, setActiveTab] = useState<"docs" | "raw">("docs");
  const [copied, setCopied] = useState(false);
  const [renderState, setRenderState] = useState<"loading" | "ok" | "error">("loading");
  const containerRef = useRef<HTMLDivElement>(null);

  const rawSpec = JSON.stringify(schema, null, 2);

  useEffect(() => {
    if (activeTab !== "docs" || !containerRef.current) return;
    setRenderState("loading");

    let cancelled = false;
    let retryTimer: NodeJS.Timeout;

    function tryRender() {
      if (cancelled) return;

      // Check all possible global names
      const standalone =
        (window as any).AsyncApiStandalone ||
        (window as any).AsyncApiComponent ||
        (window as any).asyncApiReactComponent;

      if (!standalone) {
        retryTimer = setTimeout(tryRender, 300);
        return;
      }

      try {
        if (standalone.render) {
          standalone.render(
            { schema: typeof schema === "string" ? schema : JSON.stringify(schema) },
            containerRef.current
          );
        } else if (standalone.default?.render) {
          standalone.default.render(
            { schema: typeof schema === "string" ? schema : JSON.stringify(schema) },
            containerRef.current
          );
        }
        if (!cancelled) setRenderState("ok");
      } catch (err) {
        console.error("AsyncAPI render error:", err);
        if (!cancelled) setRenderState("error");
      }
    }

    // Start trying after a small delay
    retryTimer = setTimeout(tryRender, 100);

    return () => {
      cancelled = true;
      clearTimeout(retryTimer);
      if (containerRef.current) containerRef.current.innerHTML = "";
    };
  }, [schema, activeTab]);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(rawSpec);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [rawSpec]);

  return (
    <div className="flex flex-col h-[850px] border rounded-xl overflow-hidden bg-card shadow-sm">
      <div className="flex items-center justify-between px-4 py-3 bg-muted/50 border-b">
        <div className="flex gap-1 p-1 bg-muted rounded-lg">
          <button
            onClick={() => setActiveTab("docs")}
            className={cn(
              "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
              activeTab === "docs"
                ? "bg-background shadow-sm text-primary"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            <Eye size={16} /> Documentation
          </button>
          <button
            onClick={() => setActiveTab("raw")}
            className={cn(
              "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
              activeTab === "raw"
                ? "bg-background shadow-sm text-primary"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            <Code size={16} /> JSON Spec
          </button>
        </div>

        <div className="flex items-center gap-2">
          <Badge variant={isAutoGenerated ? "secondary" : "outline"}>
            {isAutoGenerated ? (
              <><Sparkles size={12} className="mr-1" /> Auto-generated</>
            ) : (
              <><Pencil size={12} className="mr-1" /> Manually edited</>
            )}
          </Badge>
          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? <><Check size={14} className="mr-1" /> Copied</> : <><Copy size={14} className="mr-1" /> Copy</>}
          </Button>
          {onExportYaml && (
            <Button variant="default" size="sm" onClick={onExportYaml}>
              <Download size={14} className="mr-1" /> Export YAML
            </Button>
          )}
        </div>
      </div>

      <div className="flex-1 overflow-auto">
        {activeTab === "docs" ? (
          <div className="relative">
            {renderState === "loading" && (
              <div className="flex items-center justify-center h-64">
                <Loader2 size={24} className="animate-spin text-muted-foreground" />
              </div>
            )}
            {renderState === "error" && (
              <div className="flex items-center justify-center h-64 text-destructive">
                <AlertCircle size={20} className="mr-2" />
                Failed to render — try the JSON Spec tab.
              </div>
            )}
            <div
              ref={containerRef}
              className="asyncapi-custom-container p-4 bg-white"
              style={{ color: "#1a1a1a", display: renderState === "loading" ? "none" : "block" }}
            />
          </div>
        ) : (
          <div className="h-full bg-zinc-950 p-6 font-mono text-sm text-emerald-400 overflow-auto">
            <pre>{rawSpec}</pre>
          </div>
        )}
      </div>
    </div>
  );
}