// src/components/asyncapi/asyncapi-viewer.tsx
// AsyncAPI Viewer — renders spec with @asyncapi/react-component + raw YAML tab
//
// Placement: frontend/src/components/asyncapi/asyncapi-viewer.tsx

"use client";

import React, { useState, useCallback } from "react";
import dynamic from "next/dynamic";
import { Eye, Code, Copy, Check, Download, Sparkles, Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";

import "@asyncapi/react-component/styles/default.min.css";

import type { ComponentType } from "react";

interface AsyncApiProps {
  schema: string | Record<string, unknown>;
  config?: Record<string, unknown>;
}

const AsyncApiComponent = dynamic(
  () => import("@asyncapi/react-component") as Promise<{ default: ComponentType<AsyncApiProps> }>,
  {
    ssr: false,
    loading: () => (
      <div className="flex items-center justify-center h-64 text-muted-foreground animate-pulse">
        Loading AsyncAPI renderer...
      </div>
    ),
  }
);

interface AsyncApiViewerProps {
  schema: Record<string, unknown>;
  isAutoGenerated?: boolean;
  onExportYaml?: () => void;
}

export function AsyncApiViewer({
  schema,
  isAutoGenerated = true,
  onExportYaml,
}: AsyncApiViewerProps) {
  const [activeTab, setActiveTab] = useState<"docs" | "raw">("docs");
  const [copied, setCopied] = useState(false);
  console.log("VIEWER RECEIVED:", typeof schema, schema ? Object.keys(schema) : "null")
  const rawSpec = JSON.stringify(schema, null, 2);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(rawSpec);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [rawSpec]);

  return (
    <div className="flex flex-col h-[850px] border rounded-xl overflow-hidden bg-card shadow-sm">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 bg-muted/50 border-b">
        {/* Tab switcher */}
        <div className="flex gap-1 p-1 bg-muted rounded-lg">
          <button
            onClick={() => setActiveTab("docs")}
            className={cn(
              "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
              activeTab === "docs"
                ? "bg-background shadow-sm text-primary"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            <Eye size={16} /> Documentation
          </button>
          <button
            onClick={() => setActiveTab("raw")}
            className={cn(
              "flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md transition-all",
              activeTab === "raw"
                ? "bg-background shadow-sm text-primary"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            <Code size={16} /> JSON Spec
          </button>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          <Badge variant={isAutoGenerated ? "secondary" : "outline"}>
            {isAutoGenerated ? (
              <><Sparkles size={12} className="mr-1" /> Auto-generated</>
            ) : (
              <><Pencil size={12} className="mr-1" /> Manually edited</>
            )}
          </Badge>

          <Button variant="outline" size="sm" onClick={handleCopy}>
            {copied ? (
              <><Check size={14} className="mr-1" /> Copied</>
            ) : (
              <><Copy size={14} className="mr-1" /> Copy</>
            )}
          </Button>

          {onExportYaml && (
            <Button variant="default" size="sm" onClick={onExportYaml}>
              <Download size={14} className="mr-1" /> Export YAML
            </Button>
          )}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto">
        {activeTab === "docs" ? (
          <div className="asyncapi-custom-container p-4 bg-white dark:bg-zinc-950">
            <AsyncApiComponent schema={schema} />
          </div>
        ) : (
          <div className="h-full bg-zinc-950 p-6 font-mono text-sm text-emerald-400 overflow-auto">
            <pre>{rawSpec}</pre>
          </div>
        )}
      </div>
    </div>
  );
}